Upgrade to chia-blockchain 1.8
Chia-Network/internal-custody pull request #56
Opened 2023-05-14 18:55 UTC by jack60612

2023-05-15 19:43 UTC, wjblanke approved these changes, later dismissed
aok

2023-05-15 20:20 UTC, Quexington submitted a review, later dismissed

2023-05-15 20:37 UTC, jack60612 commented
Not ok

2023-05-20 02:20 UTC, wallentx requested changes

2023-05-20 02:20 UTC, wallentx commented on setup.py
> +    "chia-blockchain==1.8.0",
```suggestion
    "chia-blockchain==1.8.1",
```

2025-07-10 23:40 UTC, closed without merging